---
- hosts: "{{ host }}"
  gather_facts: true
  vars:
    access_key: YOUR ACCESS KEY
    secret_key: YOUR SECRET KEY
  tasks:
    - name: Provision instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ access_key}}"
        aws_secret_key: "{{ secret_key }}"
        key_name: "{{ pem_key }}"
        instance_type: t2.micro
        image_id: ami-05fa00d4c63e32376
        wait: yes
        count: 1
        region: us-east-1
        tags:
          Name: test-ec2